{% set version = "1.0.0" %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-ezcox
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/ezcox_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/ezcox/ezcox_{{ version }}.tar.gz
  sha256: 925ea2b0f04f39c229acb69f0d1c2f8af4d84d5806e22b45c310165ef3b6f6e9

build:
  merge_build_host: true  # [win]
  number: 0
  noarch: generic

  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]

  host:
    - r-base
    - r-dplyr >=0.8.3
    - r-forestmodel
    - r-ggplot2
    - r-magrittr >=1.5
    - r-purrr >=0.3.2
    - r-rlang >=0.1.2
    - r-survival

  run:
    - r-base
    - r-dplyr >=0.8.3
    - r-forestmodel
    - r-ggplot2
    - r-magrittr >=1.5
    - r-purrr >=0.3.2
    - r-rlang >=0.1.2
    - r-survival

test:
  commands:
    - $R -e "library('ezcox')"           # [not win]
    - "\"%R%\" -e \"library('ezcox')\""  # [win]

about:
  home: https://github.com/ShixiangWang/ezcox

  license: GPL-2.0-or-later
  summary: A tool to operate a batch of univariate or multivariate Cox models and return tidy result.

  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
    - ShixiangWang
